### ISSUE TITLE
SRECFIX  Small than 1 

### ISSUE THREAD

**Issue by daniellumertz** [ldrolez/clyphx-live10#11]
using a SRECFIX less than 1 like
`SRECFIX 0.5`
makes the same as  SRECFIX 1

in contrast 
`sel/addclip sel 0.5 `
will have the desired effect of inserting a clip of half bar

**Comment by ldrolez** [comment]
Hi!

I've tried with Live 11, and it works, I can even start a SRECFIX 0.2 on an audio track.
Please note that if you try SRECFIX on a MIDI track, then you should disable global quantization,
or lower it. That's a limitation in Live.

Could you please confirm?
-- 
Ludo

https://drolez.com/freemidi/   - Ultimate Free MIDI chords pack!
https://palmopensource.com     - Tech and hacks blog

**Comment by daniellumertz** [comment]
ah, yeah my mistake sorry!
