### ISSUE TITLE
Small question about clips being launched

### ISSUE THREAD

**Issue by Jonny0815** [ldrolez/clyphx-live10#13]
Hello, im altering your code for my purpose becuase it seems to provide a lot of what i need, but ive run into a little bit of a brick wall. when a clip starting with "[]" is launched, action_dispatch gets called by handle_action_list_trigger (correct?) but when a clip without [] is launched that doesnt happen, where do i need to take a look in order to be able to evaluate every clip thats launched?

thanks for you great work and hopefully for some help
Johannes

**Comment by ldrolez** [comment]
Did you find it?
https://github.com/ldrolez/clyphx-live10/blob/3584489bf7b0963dd31d3824bb7c8b143d061bb0/ClyphX/ClyphX.py#L207

**Comment by Jonny0815** [comment]
yea i did, thats why i closed it, but thanks for your help anyway 

im just getting started and its a hard learning curve, im usually a c++ developer and the missing datatypes are a huge toll on my reading/unerstanding speed :/ the clyphx script doesnt use a lot of the framework classes, if you can spare the time, can you give me short summary of how you interact with live? i dont think i got the hang of it yet

thanks a lot, grateful for any help 😃
