### ISSUE TITLE
import subprocess

### ISSUE THREAD

**Issue by lebrunthibault** [ldrolez/clyphx-live10#2]
Hi !

I just wanted to ask you if you managed to use import subprocess in Live 11 ?
I was under the impression it was used in ClyphPro but now I cannot find a way to spawn a process with the Live bundled python 3 version.
import subprocess works well on ableton 10 / python 2.7 (seems ableton 11 ships a "light" python build with e.g. msvcrt module missing)

Thanks !

**Comment by ldrolez** [comment]
sorry I have no idea...

**Comment by lebrunthibault** [comment]
thanks anyway :)
