### ISSUE TITLE
Clyph doesn't appears in the link tempo midi menu 

### ISSUE THREAD

**Issue by Vinch02** [ldrolez/clyphx-live10#20]
Till I made the update for live 11.1 clyphx doesn't appears in the midi menu any more.
I try your new version for the update but not working.
It seems that the py file doesn't compiled.
Any idea?

**Comment by ldrolez** [comment]
That's strange, I can't reproduce this...

**Comment by Vinch02** [comment]
OK I solved the problem. I unzipped the folder in the midi remote script but I only had to copy the folder named clyphx and note the biggest one with the read me etc.
Maybe you should change the read me folder?
Not the same post but the cs code doesn't work in my live set. Did you repair it?

**Comment by ldrolez** [comment]
Sorry could you open another issue for the CS problem?
