### ISSUE TITLE
WAIT, WAITS not working

### ISSUE THREAD

**Issue by adhechris** [ldrolez/clyphx-live10#29]
It's not working on Live 11, MBP M1.

**Comment by chebochini** [comment]
WAITS is not working on Ableton 10

**Comment by ldrolez** [comment]
Just a quick note for reference:
WAITS is not needed, just split this to 2 Clyphx commands in 2 clips. Then add a Follow Action on the 1st clip to trigger the 2nd clip after 2 bars.
https://www.ableton.com/en/live-manual/12/launching-clips/#follow-actions

For automated recording ClyphX is not needed, you can do this 100% with Live Clip follow actions and Scene follow actions.
I have a blog article on that subject: https://drolez.com/blog/music/live-looping-with-ableton-live.php#follow

**Comment by ldrolez** [comment]
Hi! In release 2.7.6, WAIT and WAITS actions were added. Please test. The main problem is a 100ms-200ms delay because the way the remote script works. Thanks!
