### ISSUE TITLE
LOADDEV 

### ISSUE THREAD

**Issue by ADrop19** [ldrolez/clyphx-live10#3]
Hello, installed ClyphX minutes ago and made a quick test using clips and actions such as DUPESCENE, MUTE ON, DEL...
All work fine.
However the LOADDEV Utility (for example), doesn't work. It stops the script from working at all
I then go to preferences to reload ClyphX in the midi tab, and the limited actions work again..

Any special reason why LOADDEV would do that ?
Thank you

**Comment by ldrolez** [comment]
Confirmed! Got this error in my logs:

2021-05-15T17:42:08.188525: info: RemoteScriptError:   File "\Remote Scripts\ClyphX11\ClyphXGlobalActions.py", line 379, in load_device
    for main_tag in self.application().browser.tags:

2021-05-15T17:42:08.188580: info: RemoteScriptError: 
2021-05-15T17:42:08.188656: info: RemoteScriptError: AttributeError: 'Browser' object has no attribute 'tags'

**Comment by ldrolez** [comment]
I have just added a basic fix to make LOADDEV work with instruments, midi effect. For an unknown reason, loading audio effects work with Live 10 but not Live 11. I suspect that the device names have changed...

**Comment by ADrop19** [comment]
Yes LOADDEV works with instrument now cool.
What i've noticed in live 11 is that the effects are now categorized into folders. 
Might that be a reason why ? The scripts needs an update to include the path of these folders maybe ?

I'd like to give a shot at working with the code (used to code a while back), could you point me to which file(s) specifically I should focus on to tinker with the actions ? I saw that notepad++ can be used to  read .py files right ?
Thank you !

**Comment by ldrolez** [comment]
Yes that's what I thought about the folders, so I tried to add some variations but it did not work.

Yes you can simply use notepad++. Just check that you use the same indentation as Python is very strict.

The devices names mapping is at the end of the consts.py file
https://github.com/ldrolez/clyphx-live10/blob/852bb649e4c4a9407745706a14f7c4e491db605d/ClyphX/consts.py#L229
