### ISSUE TITLE
Push 2

### ISSUE THREAD

**Issue by masonmcclanahan** [ldrolez/clyphx-live10#32]
I am using ClyphX with Ableton 11 and a Push 2 in session mode. When ClyphX is activate, there is a green 8x8 grid selector box that appears, but it does not synchronize with the red 8x8 grid selector box that is recognized by Push 2. This causes track column names to become mismatched with the clips as they appear on the session grid.

**Comment by ldrolez** [comment]
Ok seems to be specific to the Push 2.

I could not reproduce this bug with a Launchpad Pro or X.

**Comment by ldrolez** [comment]
Cannot reproduce without a push 2
