### ISSUE TITLE
Clyphx XT for Live 11

### ISSUE THREAD

**Issue by woorszt** [ldrolez/clyphx-live10#41]
Hi Idolez,

great work on your end! 2.7.3 is running perfectly on my Live 11 instance.

However, are there any plans to add support for ClyphX XT as well?
I have a rather complicated multi MIDI controller setup which i would love to integrate in Live 11

I found here's version 1.0.4: https://app.box.com/s/pi11ioyjx5

Cheers

**Comment by ldrolez** [comment]
Hi! Great to hear that the basic functions work well :)
Unfortunately I have very little time for this project, and I just try to fix the most easy bugs. Adding more features would require more contributors...

**Comment by ldrolez** [comment]
Not enough contributors
