### ISSUE TITLE
Metronome Rhythm command

### ISSUE THREAD

**Issue by mellbergsimon** [ldrolez/clyphx-live10#46]
Hi Stray,

Is it possible to add control to change rhythm/subdivision of the metronome.

<img width="241" alt="Skärmavbild 2023-10-10 kl  21 53 21" src="https://github.com/ldrolez/clyphx-live10/assets/44090336/07063499-0359-4e69-ae9e-c2106f1dced6">

Best Regards
Simon

**Comment by ldrolez** [comment]
There is no Live api for this
