### ISSUE TITLE
RAMP in TRACK VOL

### ISSUE THREAD

**Issue by sfogar** [ldrolez/clyphx-live10#47]
Hi, more a question than an issue.
I'd like to know it you can use a RAMP in a a TRACK VOL.
Thanks
Bye
AF

**Comment by sfogar** [comment]
Thanks, very nice !

**Comment by ldrolez** [comment]
Updated the documentation here: https://github.com/ldrolez/clyphx-live10/blob/master/reference.md#snap-tracks
