### ISSUE TITLE
macros.txt

### ISSUE THREAD

**Issue by richiewarburton** [ldrolez/clyphx-live10#8]
So happy to be back using ClyphX after a dry few months since upgrading to Live 11. Thank you! Syntax is neater BTW :-).
Question about using the $<macroname>$ convention in X-Clips where the $<macroname>$ is defined in 
/Users/<username>/nativeKONTROL/ClyphX_Pro/Macros.txt
Is that still a thing, and if so, what's the new path?

**Comment by ldrolez** [comment]
Hi! Unfortunately the $$ macros are specific to clyphx pro...
But I've heard that Pro is being ported to Live 11 :)
