### ISSUE TITLE
User Controls are working? 

### ISSUE THREAD

**Issue by daniellumertz** [ldrolez/clyphx-live10#9]
Hey people I have used clyph X pro before with v10 trying this now in v11 . It is working I can make cells perform actions when triggered, although I am not being lucky in triggering actions with MIDI in Xcontrol

Without getting complex
I am sending MIDI CC27 ch5 from TouchOSC bridge, Ableton can recognize the MIDI getting IN when I enable it as a MIDI Ports

But even though I am putting ClyphX just in control Surfaces with touchosc The messages are not triggering nothing. The MIDI is comming, it is just not triggering the actions (?)

This is my settings
![image](https://user-images.githubusercontent.com/76976666/126942498-9e58d269-8fc7-4241-bda7-583084fe0ad8.png)

In UserSettings.txt
I just have this simple exemple under USER CONTROL, 
`btn_1 = cc , 5, 27, 1/MUTE `

**Comment by ldrolez** [comment]
You can also put the scripts folder in your "User Library", under a folder "Remote Scripts" that you should create.
This way Clyphx is available to all Live versions :)

**Comment by daniellumertz** [comment]
Oh nice to know! Thanks
